# API group is batch version is v1beta1
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-fifteen-minutes
spec:
    # this job should run at the 0,15,30 and 45 minutes of every hour, every day
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      # the template fro the Job resources that  will be created by this CronJob
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: 844348677/batch-job
