apiVersion: v1
kind: pod
metadata:
  name: kubia-liveness
spec:
  containers:
    - image: 844348677/kubia-unhealthy
      name: kubia
      livenessProbe:
        httpGet:
          path: /
          port: 8080
          