apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job
spec:
  # this job must ensure five pods complete successfully
  completions: 5
  # Up to two pods can run in parallel
  parallelism: 2
  #
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job