version: '2'
services:
    testserver:
        image: testserver
    curl:
        image: appropriate/curl
        entrypoint: sh -c "sleep 8  && curl -XPOST testserver:8080/helloworld -d'{\"name\":\"Nic\"}'"